[tox]
skipsdist = true
envlist = py312, py313, py314

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
passenv = PYTHON_VERSION
allowlist_externals = uv
commands =
    uv sync --python {envpython} --all-extras --group plugins
    uv run python -m pytest --doctest-modules tests contrib/agentseek-schedule-sqlalchemy/src/tests --cov --cov-config=pyproject.toml --cov-report=xml
    ty check src tests contrib/agentseek-schedule-sqlalchemy/src contrib/agentseek-schedule-sqlalchemy/src/tests
